### ISSUE TITLE
Unable to start after deleting GameGuard    code 153

### ISSUE THREAD

**Issue by Xiao-yux** [Zinedinarnaut/helldivers-2-bypasser#1]
![image](https://github.com/user-attachments/assets/3b268b72-08d1-4412-8b30-112a1ba51cd8)

**Comment by Xiao-yux** [comment]
![image](https://github.com/user-attachments/assets/2e037848-a6bb-4097-9e40-6f117fd7b8ac)

**Comment by Xiao-yux** [comment]
If you do not delete the GameGuard file, you can enter the game after startup, and the game will crash within a few minutes after injecting the dll. If the game is started normally, the dll will crash immediately after injection

**Comment by NeoLTK** [comment]
In my case, it does not find the game folder, Even if the executable and the dll are in the bin folder of the game
so I added the hard return of my game location.

However, same error as Xiao-yux
This repository appears to be obsolete

![image](https://github.com/user-attachments/assets/f0b2fa86-45ef-4f2e-ba4a-30f910a0f7bc)

**Comment by Zinedinarnaut** [comment]
I honestly haven't worked on this for a long time now
